name: release

on:
  workflow_run:
    workflows: [build]
    branches: [v**]
    types: [completed]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    # Kinda bad since it might release on any branch starting with v, but it'll do for now.
    # Tag filtering in "on:" doesn't work, since the inital build trigger gets lost.
    # github.ref is therefore also being reset to "refs/head/master".
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download windows artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build.yml
          name: spoon.exe

      - name: Create pre-release
        uses: softprops/action-gh-release@v1
        if: ${{ contains(github.ref, 'pre') }}
        with:
          name: ${{ github.event.workflow_run.head_branch }}
          tag_name: ${{ github.event.workflow_run.head_branch }}
          prerelease: true
          files: |
            spoon.exe

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: ${{ ! contains(github.ref, 'pre') }}
        with:
          name: ${{ github.event.workflow_run.head_branch }}
          tag_name: ${{ github.event.workflow_run.head_branch }}
          prerelease: false
          files: |
            spoon.exe
